// flow-typed signature: 24990669427442524a10cb3e09d71e06
// flow-typed version: <<STUB>>/apisauce_v^0.6.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apisauce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'apisauce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apisauce/dist/apisauce' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apisauce/dist/apisauce.js' {
  declare module.exports: $Exports<'apisauce/dist/apisauce'>;
}
