// flow-typed signature: aaf71e74455bb54e2fe736577360dc52
// flow-typed version: <<STUB>>/reactotron_v^0.9.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactotron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactotron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactotron/bin/reactotron' {
  declare module.exports: any;
}

declare module 'reactotron/dist/client' {
  declare module.exports: any;
}

declare module 'reactotron/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactotron/bin/reactotron.js' {
  declare module.exports: $Exports<'reactotron/bin/reactotron'>;
}
declare module 'reactotron/dist/client.js' {
  declare module.exports: $Exports<'reactotron/dist/client'>;
}
declare module 'reactotron/dist/index.js' {
  declare module.exports: $Exports<'reactotron/dist/index'>;
}
declare module 'reactotron/index' {
  declare module.exports: $Exports<'reactotron'>;
}
declare module 'reactotron/index.js' {
  declare module.exports: $Exports<'reactotron'>;
}
